name: sent
channels:
  - conda-forge
  - defaults
dependencies:
  - aenum=3.1.15=pyhd8ed1ab_0
  - anyio=3.7.0=pyhd8ed1ab_1
  - aom=3.5.0=hf0c8a7f_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39ha30fb19_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - blinker=1.6.2=pyhd8ed1ab_0
  - blosc=1.21.4=heccf04b_0
  - boto3=1.26.161=pyhd8ed1ab_0
  - botocore=1.29.161=pyhd8ed1ab_0
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli=1.0.9=hb7f2c08_8
  - brotli-bin=1.0.9=hb7f2c08_8
  - brotlipy=0.7.0=py39ha30fb19_1005
  - brunsli=0.1=h046ec9c_0
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.19.1=h0dc2134_0
  - c-blosc2=2.9.3=h0dcb076_0
  - ca-certificates=2023.5.7=h8857fd0_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39h131948b_3
  - cfitsio=4.2.0=hd56cc12_0
  - charls=2.4.2=he965462_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - contourpy=1.1.0=py39h8ee36c8_0
  - cryptography=41.0.1=py39he8b0a07_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses-json=0.5.7=pyhd8ed1ab_0
  - dav1d=1.2.1=h0dc2134_0
  - debugpy=1.6.7=py39h7a8716b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - editables=0.3=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - flit-core=3.9.0=pyhd8ed1ab_0
  - folium=0.14.0=pyhd8ed1ab_0
  - fonttools=4.40.0=py39hdc70f33_0
  - freetype=2.12.1=h3f81eb7_1
  - geos=3.11.2=hf0c8a7f_0
  - giflib=5.2.1=hb7f2c08_3
  - hatchling=1.18.0=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - imagecodecs=2023.1.23=py39hd51fd57_2
  - importlib-metadata=6.7.0=pyha770c72_0
  - importlib-resources=5.12.0=pyhd8ed1ab_0
  - importlib_metadata=6.7.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - ipykernel=6.23.3=pyh5fb750a_0
  - ipython=8.14.0=pyhd1c38e8_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=8.3.0=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py39h6e9494a_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.7.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jxrlib=1.1=h35c211d_2
  - kiwisolver=1.4.4=py39h92daf61_1
  - krb5=1.20.1=h049b76e_0
  - lcms2=2.15=h2dcdeff_1
  - lerc=4.0.0=hb486fe8_0
  - libaec=1.0.6=hf0c8a7f_1
  - libavif=0.11.1=h22361c6_2
  - libblas=3.9.0=17_osx64_openblas
  - libbrotlicommon=1.0.9=hb7f2c08_8
  - libbrotlidec=1.0.9=hb7f2c08_8
  - libbrotlienc=1.0.9=hb7f2c08_8
  - libcblas=3.9.0=17_osx64_openblas
  - libcurl=8.1.2=hbee3ae8_0
  - libcxx=16.0.6=hd57cbcb_0
  - libdeflate=1.18=hac1461d_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=11_3_0_h97931a8_31
  - libgfortran5=12.2.0=he409387_31
  - libjpeg-turbo=2.1.5.1=hb7f2c08_0
  - liblapack=3.9.0=17_osx64_openblas
  - libnghttp2=1.52.0=he2ab024_0
  - libopenblas=0.3.23=openmp_h429af6e_0
  - libpng=1.6.39=ha978bb4_0
  - libsodium=1.0.18=hbcb3906_1
  - libsqlite=3.42.0=h58db7d2_0
  - libssh2=1.11.0=hd019ec5_0
  - libtiff=4.5.1=hf955e92_0
  - libwebp-base=1.3.0=hb7f2c08_0
  - libxcb=1.15=hb7f2c08_0
  - libzlib=1.2.13=h8a1eda9_5
  - libzopfli=1.0.3=h046ec9c_0
  - llvm-openmp=16.0.6=hff08bdf_0
  - lz4-c=1.9.4=hf0c8a7f_0
  - markupsafe=2.1.3=py39hdc70f33_0
  - marshmallow=3.19.0=pyhd8ed1ab_0
  - marshmallow-enum=1.5.1=pyh9f0ad1d_3
  - matplotlib=3.7.1=py39h6e9494a_0
  - matplotlib-base=3.7.1=py39hb2f573b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=3.0.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - nbclassic=1.0.0=pyhb4ecaf3_1
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.6.0=pyhd8ed1ab_0
  - nbconvert-core=7.6.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.6.0=pyhd8ed1ab_0
  - nbformat=5.9.0=pyhd8ed1ab_0
  - ncurses=6.4=hf0c8a7f_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook=6.5.4=pyha770c72_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - numpy=1.25.0=py39h892e69a_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.0=h13ac156_2
  - openssl=3.1.1=h8a1eda9_1
  - overrides=7.3.1=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandoc=3.1.3=h9d075a6_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.11.1=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.5.0=py39he6683de_1
  - pip=23.1.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.8.0=pyhd8ed1ab_0
  - pluggy=1.2.0=pyhd8ed1ab_0
  - proj=9.2.1=hc8d59c9_0
  - prometheus_client=0.17.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.5=py39ha30fb19_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyjwt=2.7.0=pyhd8ed1ab_0
  - pyobjc-core=9.2=py39head00df_0
  - pyobjc-framework-cocoa=9.2=py39head00df_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.1.0=pyhd8ed1ab_0
  - pyproj=3.6.0=py39h359dca6_1
  - pyrsistent=0.19.3=py39ha30fb19_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.16=h709bd14_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.17.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pyyaml=6.0=py39ha30fb19_5
  - pyzmq=25.1.0=py39hdac9eea_0
  - readline=8.2=h9e318b2_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - s3transfer=0.6.1=pyhd8ed1ab_0
  - send2trash=1.8.2=pyhd1c38e8_0
  - sentinelhub=3.9.1=pyhd8ed1ab_0
  - setuptools=68.0.0=pyhd8ed1ab_0
  - shapely=2.0.1=py39h1518777_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h225ccf5_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.42.0=h2b0dec6_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - stringcase=1.2.0=py_0
  - terminado=0.17.1=pyhd1c38e8_0
  - tifffile=2023.4.12=pyhd8ed1ab_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomli-w=1.0.0=pyhd8ed1ab_0
  - tornado=6.3.2=py39hdc70f33_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - trove-classifiers=2023.5.24=pyhd8ed1ab_0
  - typing-extensions=4.6.3=hd8ed1ab_0
  - typing_extensions=4.6.3=pyha770c72_0
  - typing_inspect=0.9.0=pyhd8ed1ab_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - unicodedata2=15.0.0=py39ha30fb19_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - utm=0.7.0=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.6.1=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=h0dc2134_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=h0d85af4_2
  - zeromq=4.3.4=he49afe7_1
  - zfp=1.0.0=ha894c9a_3
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8a1eda9_5
  - zlib-ng=2.0.7=hb7f2c08_0
  - zstd=1.5.2=hbc0c0cd_6
